fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    vcsrepo: "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
  symlinks:
    apaxy: "#{source_dir}"
